env = Environment(CPPPATH=[".", "../cuilien"], CCFLAGS="-std=c99", LIBPATH="../cuilien/build")


# Source section
sources = Split("""
main.c
graphics.c
cell.c
world.c
interaction.c
mutate.c
""")


# Object section
objects = env.Object(source = sources)


# Target section
binary = env.Program(target = "bin", source = objects, LIBS = ["cuilien", "SDL"])

